name: Release CI
on: push
jobs:
  x64_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Run msbuild
      run: msbuild -p:configuration=release -p:platform=x64 -p:platformToolset=v143

    - name: Get current time
      uses: josStorer/get-current-time@v2.1.1
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+02:00"

    - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/x64/Release/TrafficMonitor.exe
          Bin/x64/Release/*.dll

    - name : Upload pdb files
      uses: actions/upload-artifact@v3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_pdb
        path: Bin/x64/Release/*.pdb
